### ISSUE TITLE
useInterval: can use return function when clear

### ISSUE THREAD

**Issue by wenzi0github** [beautifulinteractions/beautiful-react-hooks#118]
https://github.com/beautifulinteractions/beautiful-react-hooks/blob/20afd61b06936932497c01daa85d6cae97a71cb9/src/useInterval.js#L35

we can use return in useEffect:

```javascript
useEffect(() => {
    if (typeof milliseconds === 'number') {
      timeout.current = setInterval(() => {
        callback.current();
      }, milliseconds);
    }
    // cleanup previous interval
    return () => clear();
  }, [milliseconds]);
```

**Comment by antonioru** [comment]
Hi @wenzi0github 
thank you for the huge improvement you're bringing to the library! 

I'll look into this bug as soon as possibile!

**Comment by antonioru** [comment]
Thank you @wenzi0github 
I've merged your PR, it's now part of the current release
