### ISSUE TITLE
isDevelopment in webpack v5 causes an error 'process is not defined'

### ISSUE THREAD

**Issue by exKAZUu** [beautifulinteractions/beautiful-react-hooks#164]
**Describe the bug**
webpack v5 doesn't provide a mock of `process`, so `isDevelopment` causes an error 'process is not defined'.
(Note that `webpack.DefinePlugin` replace just `process.env.NODE_ENV` (not `process`), so `process` is still `undefined` even if `process.env.NODE_ENV` is available.)

**To Reproduce**
1. Build a web app depending `beautiful-react-hooks` with webpack v5
2. Open the web app
3. `Uncaught ReferenceError: process is not defined` is shown in console

**Expected behavior**
No error is shown.

**Desktop:**
 - OS: any (I use Mac OS)
 - Browser: any (I use Chrome 85)
 - Version: beautiful-react-hooks v0.30.5

**Comment by antonioru** [comment]
Hi @exKAZUu thank you for pointing this out and thank you so much for your pull request! 
I'll have a look at it as soon as possibile
