### ISSUE TITLE
useDebouncedFn docs and comment fix

### ISSUE THREAD

**Issue by endlessqt** [beautifulinteractions/beautiful-react-hooks#178]
## Comment in file useDebouncedFn.js 
```javascript
/**
 * Accepts a function and returns a new debounced yet memoized version of that same function that delays
 * its invoking by the defined time.
 * If time is not defined, its default value will be 250ms.
 */
const useDebouncedFn = (fn, wait = 100, options = defaultOptions, dependencies) => {
  const debounced = debounce(fn, wait, options);

  return useCallback(debounced, dependencies);
};

export default useDebouncedFn;
```
## I guess the right version of the comment have to be like that, because default wait value set to 100.
```javascript
/**
 * Accepts a function and returns a new debounced yet memoized version of that same function that delays
 * its invoking by the defined time.
 * If time is not defined, its default value will be 100ms.
*/
```
### Also in file useDebouncedFn.md inside "Options" paragraph
> Since useDebouncedFn uses lodash.throttle under the hood, you can possibly define few options to customize its behaviour.
>
According to useDebouncedFn.js file useDebouncedFn hook is using lodash.debounce under the hood, so options paragraph could look like that
> Since useDebouncedFn uses [lodash.debounce](https://www.npmjs.com/package/lodash.debounce) under the hood, you can possibly define few options to customize its behaviour.

**Comment by antonioru** [comment]
Hi @endlessqt 

thank you very much for opening this issue and yes I think this improvements will make a better documentation. 
Please feel free to open a MR if you can, I would be happy to review and approve
