### ISSUE TITLE
A link failure ===》🌟 Live playground here 🌟  

### ISSUE THREAD

**Issue by syc666** [beautifulinteractions/beautiful-react-hooks#199]
**Describe the bug**
![image](https://user-images.githubusercontent.com/19420681/103985886-bbbb8280-51c4-11eb-9fd3-764d6427820f.png)
The link in the red circle is broken

**Comment by asapach** [comment]
https://beautifulinteractions.github.io/beautiful-react-hooks/
```
Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    in Unknown
    in Unknown
    in CustomSidebar
    in TableOfContents
    in div
    in div
    in StyleGuideRenderer
    in Styled(StyleGuide)
    in StyleGuide
```

**Comment by antonioru** [comment]
HI @syc666 
thank you for opening this bug, I'll try to understand why the link broke as soon as possibile, in the meanwhile pull requests are welcome

**Comment by antonioru** [comment]
I'm closing this as it has been resolved with the last commit
