### ISSUE TITLE
Switch codebase to typescript

### ISSUE THREAD

**Issue by yashshah1** [beautifulinteractions/beautiful-react-hooks#214]
**Is your feature request related to a problem? Please describe.**
Switching to typescript or adding type hints can increase the usability in the long run. 

**Describe the solution you'd like**
Convert all the files one by one

**Comment by antonioru** [comment]
Hi @yashshah1 

thank you for opening this feature request, but at the moment there's no plan to switch the codebase to typescript. 
But feel free to open a PR to add the type definitions if you want

**Comment by antonioru** [comment]
I'm closing this
