### ISSUE TITLE
Incorrect MutableRefObject typings with --strictNullChecks option enabled

### ISSUE THREAD

**Issue by joxerTMD** [beautifulinteractions/beautiful-react-hooks#231]
Hi! Thx for the awesome library. I've recently faced an issue with TS typings and prepared a fix (#232) 
Here is the issue

Consider this code from the [docs](https://github.com/beautifulinteractions/beautiful-react-hooks/blob/master/docs/useViewportSpy.md) that is written in typescript
```tsx
import { useRef } from 'react';
import { useViewportSpy } from 'beautiful-react-hooks';

const ViewportSpyComponent = () => {
    const ref = useRef<HtmlElement>();
    const isVisible = useViewportSpy(ref);

    return (
        <div>
            <div ref={ref} style={{padding: '20px 0', background: '#1D6C8B'}}>
                Observed element
            </div>
            <div style={{margin: '20px 0'}}>
                is the observed element in viewport? {isVisible ? 'yes': 'no'}
            </div>
        </div>
    );
};

```
with --strictNullChecks option enabled it gives me the following errors:

1. TS2345: Argument of type 'MutableRefObject<HTMLElement | undefined>' is not assignable to parameter of type 'MutableRefObject<HTMLElement>'.   Type 'HTMLElement | undefined' is not assignable to type 'HTMLElement'.     Type 'undefined' is not assignable to type 'HTMLElement'.
2. TS2322: Type 'MutableRefObject<HTMLElement | undefined>' is not assignable to type 'LegacyRef<HTMLDivElement> | undefined'.   Type 'MutableRefObject<HTMLElement | undefined>' is not assignable to type 'RefObject<HTMLDivElement>'.     Types of property 'current' are incompatible.       Type 'HTMLElement | undefined' is not assignable to type 'HTMLDivElement | null'.         Type 'undefined' is not assignable to type 'HTMLDivElement | null'.

This issue is valid for all hooks that use MutableRefObject as argument

What can we do to fix this?
1.  Change typings from 
 ```ts
export declare const useViewportSpy: (elementRef: MutableRefObject<HTMLElement>, options?: IntersectionObserverInit) => boolean;
```
to

```ts
export declare const useViewportSpy: (elementRef: MutableRefObject<HTMLElement | null | undefined>, options?: IntersectionObserverInit) => boolean;
```
2. change the docs to favor useRef(null) over userRef()

Thx!

**Comment by antonioru** [comment]
Hi @joxerTMD 

thank you very much, I'm going to check your PR right now
