### ISSUE TITLE
useDebouncedFn clearing timeouts

### ISSUE THREAD

**Issue by ayarushin** [beautifulinteractions/beautiful-react-hooks#56]
Hey,

As I can see you don't use `debounced.cancel()` [here](https://github.com/beautifulinteractions/beautiful-react-hooks/blob/master/src/useDebouncedFn.js) for clearing timeout.
Am I right or I missed something? :)

**Comment by antonioru** [comment]
Hiya @ayarushin 
yes, you're right at the moment the `useDebouncedFn` hook does not return its cancel function, but as it is abstracted on top on Lodash it can easily implemented. 
It's a feature I'm open to welcome so if you want to contribute we can discuss how it should be done 

A

**Comment by ayarushin** [comment]
Sounds great! I'll do it

**Comment by antonioru** [comment]
@ayarushin great, man! thank you 

Please be sure to return a debounced function to avoid introducing a breaking change also make sure to document how to possibly clear the debounced one. 

The lodash approach looks quite good to me, something like:

```
const debouncedFn = useDebouncedFn(myCallback, 250);

debouncedFn.cancel(); 
```

**Comment by ayarushin** [comment]
haha, looks like we no need in a fix 😄 
i debugged and hook already returns debounced with `flush` and `cancel` methods
![изображение](https://user-images.githubusercontent.com/5379312/72921093-a5ba7500-3d5b-11ea-81b6-40f1fc9fb875.png)

**Comment by antonioru** [comment]
@ayarushin 

mmmhhh, that's weird since useCallback shall return a memoized (so a new) version of the function, perhaps it take care of keeping the static properties somehow. 

Anyway, the whole thing still needs to be documented, so feel free to open a PR about that if you want  :)
