### ISSUE TITLE
useDebouncedFn seems not debounce

### ISSUE THREAD

**Issue by linonetwo** [beautifulinteractions/beautiful-react-hooks#65]
**Describe the bug**

I'm calling useDebouncedFn in onChange

```js
  const setOutsideValue = useDebouncedFn(() => {
    console.log('called');
    
  }, 500)


  return (
    <Slate editor={editor} value={value} onChange={nextValue => {setValue(nextValue);setOutsideValue()}}>
```

And it is called as much as I type, after 500ms.

<img width="404" alt="Screen Shot 2020-02-20 at 8 25 20 PM" src="https://user-images.githubusercontent.com/3746270/74933556-351c7c00-541f-11ea-9f72-ff94cbff393e.png">

**To Reproduce**
Add later...

(Update: https://stackblitz.com/edit/react-ombwbo)

**Expected behavior**
 Only called 500ms a time.

**Desktop (please complete the following information):**
 - Electron 8.0.1

**Comment by antonioru** [comment]
Hello @linonetwo 
thank you for reporting this possible bug, can you please provide more informations? 
At the moment the `useDebouncedFn` seems working pretty fine on my end:

https://beautifulinteractions.github.io/beautiful-react-hooks/#/useDebouncedFn

**Comment by linonetwo** [comment]
@antonioru Thanks for fast response!

Please try this:

https://stackblitz.com/edit/react-ombwbo

**Comment by antonioru** [comment]
@linonetwo 
Ok I got your problem: given that `useDebouncedFn` will be performed on each render you shall provide its dependencies since it uses `useCallback` under the hood. 

you should write it this way:

```
  const setOutsideValue = useDebouncedFn(() => {
    console.log('called...');
  }, 500, null, [])
```

please let me know if this solves your problem

**Comment by antonioru** [comment]
@linonetwo also consider that `useDebounceFn` does not return a function that will be performed every 500ms it returns a debounced function, according to lodash documentation:

"Creates a debounced function that delays invoking func until after wait milliseconds have elapsed since the last time the debounced function was invoked."

if you are searching for a hook that invoke a function every x-seconds, please take a  look at `useInterval`

**Comment by linonetwo** [comment]
Thank you! I didn't notice that. 

I thought there will be a `[]` as the default value, so I didn't add one.

**Comment by linonetwo** [comment]
> I think "called2" should only be logged every 500ms.

I actually mean "when I kept typing"~

**Comment by linonetwo** [comment]
Your work is brilliant, so I have written an article to promote your lib. https://www.toutiao.com/i6794068224808845831/

**Comment by antonioru** [comment]
@linonetwo 
OMG this is lush!!! 👍 
Thank you so much, I wish I could understand Chinese! 
I don't know how to thank you :)

**Comment by antonioru** [comment]
@linonetwo 
I was wandering, perhaps if you want you can translate open a pull request for a chinese README.md so people from China can use the library too, what do you think? :) 

🇨🇳🔗🇮🇹

**Comment by linonetwo** [comment]
Absolutely OK, just wait a few days.
