### ISSUE TITLE
`useSessionStorage`

### ISSUE THREAD

**Issue by Rawnly** [beautifulinteractions/beautiful-react-hooks#82]
**Describe the solution you'd like**
I'd like to have an hook to manage [`sessionStorage`](https://developer.mozilla.org/en-US/docs/Web/API/Window/sessionStorage)

It can be done easily by copy-pasting `useLocalStorage` code and changing the window method from `window.localStorage.*` to `window.sessionStorage.*`.

**Alternatives**
An hook to manage both the storage types, something like the following:

```js
	const [count,setCount] = useStorage('local', 0)
```

**Comment by antonioru** [comment]
Hi @Rawnly 
that's is indeed a brilliant idea and I would love to receive you contribution. 

I think the best possible solution is to have a `useStorage` thunk on which to abstract both `useLocalStorage` and `useSessionStorage`, something like:

```
const useStorage = (storageType) => (initialValue) => {
    ...
}

const useLocalStorage = useStorage('local'); 
const useSessionStorage = useStorage('session'); 
```
What d'you think?

**Comment by Rawnly** [comment]
Awesome, if you’d like I can open a PR about that ✌️

**Comment by antonioru** [comment]
Of course! 
I would love to! 

🇮🇹🇮🇹🇮🇹
