### ISSUE TITLE
TypeScript: This expression is not callable. Type 'Cancelable' has no call signatures.

### ISSUE THREAD

**Issue by deevus** [beautifulinteractions/beautiful-react-hooks#83]
The TypeScript definition is incorrect for `useDebouncedFn`

https://github.com/beautifulinteractions/beautiful-react-hooks/blob/13d661285700b96fddfad3f29bec6f1e97943c63/index.d.ts#L28

The hook return a `Function` but the type is `Cancelable` which is not callable and so the following error is thrown: 

```
This expression is not callable. Type 'Cancelable' has no call signatures.
```

Suggest that a new type could be the following:

```ts
 export declare const useDebouncedFn: <F extends Function>(fn: F, wait?: number, options?: ThrottleOrDebounceOpts, dependencies?: DependencyList) => F & Cancelable; 
```

**Comment by deevus** [comment]
Happy to open a PR

**Comment by antonioru** [comment]
Hello @deevus 

I am sorry for the late response and thank you for highlighting this bug. 
I am looking forward receiving your PR 

cheers
