### ISSUE TITLE
Running useViewportSpy on server side

### ISSUE THREAD

**Issue by muhaimincs** [beautifulinteractions/beautiful-react-hooks#91]
**Describe the bug**
TypeError: Failed to execute 'observe' on 'IntersectionObserver': parameter 1 is not of type 'Element'.

**To Reproduce**
1. Use Next.js to reproduce React app
2. Setup this package and set ref to the `useViewportSpy
3. See error

**Expected behavior**
No error produce

**Screenshots**
<img width="980" alt="Screenshot 2020-06-17 at 3 04 04 PM" src="https://user-images.githubusercontent.com/30996641/84866077-cccb6780-b0ab-11ea-8ec0-cbf162948819.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome, Firefox

**Additional context**
Use Nextjs for server side rendering

**Comment by antonioru** [comment]
Hello @muhaimincs 
thank you very much for opening the issue. 
I'm not sure this is actually a problem with the library itself, it looks perhaps like you're using the `useViewportSpy` hook before the element ref exists. 
As you may've notice the hook expect an existing DOM Element ref to work. 

Please check your app lifecycle

**Comment by antonioru** [comment]
Hi @muhaimincs 
do you have any news on the issue? 
Can I close it?

**Comment by antonioru** [comment]
I am closing the issue since I've got no significant information from the author.

**Comment by tafelito** [comment]
@antonioru is it possible to make the console.warn when on SSR to be optional or at least to not run in PROD?
