### ISSUE TITLE
FYI: screenwidth example is broken in Firefox

### ISSUE THREAD

**Issue by tomByrer** [beautifulinteractions/beautiful-react-hooks#93]
**Describe the bug**
FYI: screenwidth example is broken in Firefox

**To Reproduce**
1. Go to https://beautifulinteractions.github.io/beautiful-react-hooks/#/useGlobalEvent
2. `Current window width: 1920` (even though I'm running 4k.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win10, 4k monitor
 - Browser Firefox

Works fine in Chromium.
More of a FYI; Firefox only has 5% of the market.

**Comment by antonioru** [comment]
Hello @tomByrer 

thanks for reporting the issue, can you please add more info?
Is it an issue with the library itself (like the resize event stops firing on bigger screens) or something related to styleguidist? 
 
I am trying to reproduce the bug on Firefox and other browsers (unfortunately I'm on a Mac at the moment) and it seems to work quite fine. 

Here's the screenshot: 
https://ibb.co/0K9vPZx

**Comment by antonioru** [comment]
@tomByrer any news about this issue?
